language: python

env:
    - CONDA="python=2.7"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda config --add channels ioos -f
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - conda install --yes --file requirements-dev.txt

script:
    - py.test --verbose --doctest-modules --ignore setup.py
    - find . -type f -name "*.py" | xargs flake8 --max-line-length=100
